//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DramaTheaterTestEntities : DbContext
    {
        public DramaTheaterTestEntities()
            : base("name=DramaTheaterTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Age> Age { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Performance> Performance { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<PriceCategory> PriceCategory { get; set; }
        public virtual DbSet<PriceTime> PriceTime { get; set; }
        public virtual DbSet<Script> Script { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Stat> Stat { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TypeOfUser> TypeOfUser { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
